name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          docker build -t nikitapavdev/cryptotracker:frontend-${{ github.run_number }} ./frontend
          docker push nikitapavdev/cryptotracker:frontend-${{ github.run_number }}

      - name: Build and push backend
        run: |
          docker build -t nikitapavdev/cryptotracker:backend-${{ github.run_number }} ./backend
          docker push nikitapavdev/cryptotracker:backend-${{ github.run_number }}

      - name: Build and push node-service
        run: |
          docker build -t nikitapavdev/cryptotracker:apigateway-${{ github.run_number }} ./node-service
          docker push nikitapavdev/cryptotracker:apigateway-${{ github.run_number }}

      - name: Build and push fastapi-service
        run: |
          docker build -t nikitapavdev/cryptotracker:analysis-${{ github.run_number }} ./fastapi-service
          docker push nikitapavdev/cryptotracker:analysis-${{ github.run_number }}

      - name: Trigger Render deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
