name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa github-to-gcp@34.56.114.159 << 'EOF'
          cd /home/github-to-gcp/cryptotracker
          git pull origin main
          docker compose pull
          docker compose up -d --build
        EOF
 
      - name: Deploy via SSH
        run: |
          sudo ssh -i ~/.ssh/id_rsa github-to-gcp@34.56.114.159 << 'EOF'
            cd /home/github-to-gcp/cryptotracker
            git pull origin main
            docker compose pull
            docker compose up -d --build
          EOF
