name: Deploy to GCP VM

on:
  workflow_run:
    workflows: ["Laravel Tests"] 
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_DEPLOY_KEY_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.56.114.159 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -v -i ~/.ssh/id_rsa github-to-gcp@34.56.114.159 << 'EOF'
            cd /home/github-to-gcp/docvault
            git pull origin main
            docker-compose pull
            docker-compose -f docker-compose.yml up -d --build
          EOF
