name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, sqlite, pdo_sqlite
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: backend

      - name: Set up Laravel .env
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: backend

      - name: Set up Laravel config for testing
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
        working-directory: backend

      - name: Run migrations
        run: php artisan migrate
        working-directory: backend

      - name: Run tests
        run: php artisan test
        working-directory: backend
        
  deploy:
    needs: test
    name: Deploy over SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_DEPLOY_KEY_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.56.114.159 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -v -i ~/.ssh/id_rsa github-to-gcp@34.56.114.159 << 'EOF'
            cd /home/github-to-gcp/docvault
            git pull origin main
            docker-compose pull
            docker-compose -f docker-compose.yml up -d --build
          EOF
