name: Run Laravel Tests (SQLite In-Memory)

on:
  push:
    branches:
      - main  # измени на ветку деплоя, если нужно
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, sqlite, pdo_sqlite
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
        working-directory: backend

      - name: Set up Laravel .env
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: backend

      - name: Set up Laravel config for testing
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
        working-directory: backend

      - name: Run migrations
        run: php artisan migrate
        working-directory: backend

      - name: Run tests
        run: php artisan test
        working-directory: backend

